POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "adam1", "password": "Pass1234!", "email": "adam@mail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json 
Authorization: token a64476e9cea4ca167d4de8ad9ede424037506019